# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNGimbal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNGimbal
  pod 'Gimbal'
  
  target 'RNGimbalTests' do
    use_frameworks!
    inherit! :search_paths
    
    pod 'Gimbal'
    
    pod 'React', :path => '../node_modules/react-native', subspecs: [
      'Core',
      'CxxBridge',
      'DevSupport',
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket',
      'RCTAnimation',
      'RCTActionSheet',
      'RCTBlob',
      'RCTCameraRoll',
      'RCTGeolocation',
      'RCTImage',
      'RCTPushNotification',
      'RCTSettings',
      'RCTTest',
      'RCTVibration',
      'RCTLinkingIOS'
    ]

    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  end
end
